       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTFIELDACCESS.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT GRACE-LOGFILE ASSIGN TO "users_out.dat".
           SELECT GRACE-USERSFILE ASSIGN TO "users.dat".

       DATA DIVISION.
       FILE SECTION.
       FD  GRACE-LOGFILE.
       01  GRACE-USERREC-FD-GRACE-LOGFILE.
           05 GRACE-USERID PIC 9(6).
           05 GRACE-USERNAME PIC X(20).
           05 GRACE-ISACTIVE PIC 9(1).
       FD  GRACE-USERSFILE.
       01  GRACE-USERREC-FD-GRACE-USERSFILE.
           05 GRACE-USERID PIC 9(6).
           05 GRACE-USERNAME PIC X(20).
           05 GRACE-ISACTIVE PIC 9(1).

       WORKING-STORAGE SECTION.
       01 GRACE-CURRENTUSER.
           05 GRACE-USERID PIC 9(6).
           05 GRACE-USERNAME PIC X(20).
           05 GRACE-ISACTIVE PIC 9(1).
       01 GRACE-TEMPID PIC 9(6).

      *GRACE Compiler Helper Variables
       01 GRACE-TMP-INT-1 PIC S9(18).
       01 GRACE-TMP-DISPLAY PIC Z(17)9-.
       01 GRACE-EOF-FLAG PIC X VALUE 'N'.
          88 GRACE-EOF-FLAG-REACHED VALUE 'Y'.

       PROCEDURE DIVISION.
       MAIN SECTION.
           OPEN INPUT GRACE-USERSFILE OUTPUT GRACE-LOGFILE.
           COMPUTE GRACE-TEMPID = 0.
           DISPLAY "Reading user...".
       READ GRACE-USERSFILE INTO GRACE-CURRENTUSER
           AT END SET GRACE-EOF-FLAG-REACHED TO TRUE
       END-READ.
           DISPLAY "User ID:".
           DISPLAY GRACE-USERID OF GRACE-CURRENTUSER.
           DISPLAY "User Name:".
           DISPLAY GRACE-USERNAME OF GRACE-CURRENTUSER.
           DISPLAY "Activating user...".
           COMPUTE GRACE-ISACTIVE OF GRACE-CURRENTUSER = 1.
      *Expression too long for single COMPUTE ...
      *Begin multi-step COMPUTE for GRACE-TEMPID
           COMPUTE GRACE-TMP-INT-1= 
      - GRACE-USERID OF GRACE-CURRENTUSER + 100000.
           COMPUTE GRACE-TEMPID = GRACE-TMP-INT-1.
      *End multi-step COMPUTE for GRACE-TEMPID
           DISPLAY "Temp ID:".
           DISPLAY GRACE-TEMPID.
           DISPLAY "Writing log...".
           WRITE GRACE-USERREC-FD-GRACE-LOGFILE FROM GRACE-CURRENTUSER.
           DISPLAY "Done.".
           CLOSE GRACE-LOGFILE GRACE-USERSFILE.
           GOBACK.
