       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTHELLO.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-GREETING PIC X(5).
       01 GRACE-NAME PIC X(5).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE "Hello" TO GRACE-GREETING.
           MOVE "Arnav" TO GRACE-NAME.
           DISPLAY GRACE-GREETING.
           DISPLAY GRACE-NAME.
           GOBACK.
