       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTREASSIGNMENT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-COUNTER PIC 9(2).
       01 GRACE-MESSAGE PIC X(7).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE "Initial" TO GRACE-MESSAGE.
           DISPLAY GRACE-MESSAGE.
           MOVE "Changed" TO GRACE-MESSAGE.
           DISPLAY GRACE-MESSAGE.
           COMPUTE GRACE-COUNTER = 10.
           DISPLAY GRACE-COUNTER.
           COMPUTE GRACE-COUNTER = 20.
           DISPLAY GRACE-COUNTER.
           GOBACK.
