       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTSTRINGWIDTH.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-COPY-LONG PIC X(55).
       01 GRACE-EXACT-STR PIC X(30).
       01 GRACE-LONG-STR PIC X(55).
       01 GRACE-SHORT-STR PIC X(5).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE "Hello" TO GRACE-SHORT-STR.
           MOVE "123456789012345678901234567890" TO GRACE-EXACT-STR.
           MOVE "This string is intentionally longer than 30 characters
      -"." TO GRACE-LONG-STR.
           MOVE GRACE-LONG-STR TO GRACE-COPY-LONG.
           DISPLAY GRACE-SHORT-STR.
           DISPLAY GRACE-EXACT-STR.
           DISPLAY GRACE-LONG-STR.
           DISPLAY GRACE-COPY-LONG.
           GOBACK.
