       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTEXPLICITINT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-A PIC 9(5).

       PROCEDURE DIVISION.
       MAIN SECTION.
           COMPUTE GRACE-A = 12345.
           DISPLAY GRACE-A.
           GOBACK.
