       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTEXPLICITINT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-A PIC 9(5).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE 12345 TO GRACE-A.
           DISPLAY GRACE-A.
           GOBACK.
