       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTINT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-ANOTHER PIC 9(1).
       01 GRACE-COUNT PIC 9(3).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE 123 TO GRACE-COUNT.
           DISPLAY GRACE-COUNT.
           MOVE 0 TO GRACE-ANOTHER.
           DISPLAY GRACE-ANOTHER.
           GOBACK.
