       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTEXPLICITTYPESTRING.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 S PIC X(30).

       PROCEDURE DIVISION.

       MAIN SECTION.
           MOVE "Explicit String" TO S.
           DISPLAY S.
           GOBACK.
