       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTVARASSIGN.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-DEST PIC 9(2).
       01 GRACE-S-DEST PIC X(3).
       01 GRACE-S-SOURCE PIC X(3).
       01 GRACE-SOURCE PIC 9(2).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE 42 TO GRACE-SOURCE.
           MOVE GRACE-SOURCE TO GRACE-DEST.
           DISPLAY GRACE-DEST.
           MOVE "abc" TO GRACE-S-SOURCE.
           MOVE GRACE-S-SOURCE TO GRACE-S-DEST.
           DISPLAY GRACE-S-DEST.
           GOBACK.
