       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTMIXEDPARAMS.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-STATUSMSG PIC X(30).
       01 GRACE-STATUSMSG2 PIC X(30).
       01 GRACE-USERACTIVE PIC 9(1).
       01 GRACE-USERID PIC 9(8).
       01 GRACE-USERNAME PIC X(15).

      *GRACE Procedure Return Variables
       01 GRACE-RET-PROCESSDATA PIC X(30).

       LOCAL-STORAGE SECTION.
      *Locals & Params for procedure 'processData'
       01 GRACE-PROCESSDATA-ACTIVE PIC 9(1).
       01 GRACE-PROCESSDATA-ID PIC 9(8).
       01 GRACE-PROCESSDATA-NAME PIC X(25).

       PROCEDURE DIVISION.
       DECLARATIVES.
       GRACE-PROCESSDATA SECTION.
      *proc processData(id: int(8), name: string(25), active: int(1)): string(30)
           DISPLAY "Processing Data...".
           DISPLAY GRACE-PROCESSDATA-ID.
           DISPLAY GRACE-PROCESSDATA-NAME.
           DISPLAY GRACE-PROCESSDATA-ACTIVE.
           MOVE "Processed Record" TO GRACE-RET-PROCESSDATA.
           EXIT SECTION.

       END DECLARATIVES.

       MAIN SECTION.
           MOVE 12345678 TO GRACE-USERID.
           MOVE "Test User Alpha" TO GRACE-USERNAME.
           MOVE 1 TO GRACE-USERACTIVE.
           MOVE GRACE-USERID TO GRACE-PROCESSDATA-ID.
           MOVE GRACE-USERNAME TO GRACE-PROCESSDATA-NAME.
           MOVE GRACE-USERACTIVE TO GRACE-PROCESSDATA-ACTIVE.
           PERFORM GRACE-PROCESSDATA.
           MOVE GRACE-RET-PROCESSDATA TO GRACE-STATUSMSG.
           DISPLAY GRACE-STATUSMSG.
           MOVE 987 TO GRACE-PROCESSDATA-ID.
           MOVE "Beta" TO GRACE-PROCESSDATA-NAME.
           MOVE 0 TO GRACE-PROCESSDATA-ACTIVE.
           PERFORM GRACE-PROCESSDATA.
           MOVE GRACE-RET-PROCESSDATA TO GRACE-STATUSMSG2.
           DISPLAY GRACE-STATUSMSG2.
           GOBACK.
