       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTEXPLICITTYPEINT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 A PIC 9(6).

       PROCEDURE DIVISION.
           MOVE 12345 TO A.
           DISPLAY A.
           STOP RUN.
