       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTLARGELITERALWIDTH.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-LARGE PIC 9(7).
       01 GRACE-MEDIUM PIC 9(6).
       01 GRACE-SMALL PIC 9(3).
       01 GRACE-TOOLARGE PIC 9(9).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE 123 TO GRACE-SMALL.
           MOVE 123456 TO GRACE-MEDIUM.
           MOVE 1234567 TO GRACE-LARGE.
           MOVE 987654321 TO GRACE-TOOLARGE.
           DISPLAY GRACE-SMALL.
           DISPLAY GRACE-MEDIUM.
           DISPLAY GRACE-LARGE.
           DISPLAY GRACE-TOOLARGE.
           GOBACK.
