       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTLARGELITERALWIDTH.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 LARGE PIC 9(7).
       01 MEDIUM PIC 9(6).
       01 SMALL PIC 9(6).
       01 TOOLARGE PIC 9(9).

       PROCEDURE DIVISION.
           MOVE 123 TO SMALL.
           MOVE 123456 TO MEDIUM.
           MOVE 1234567 TO LARGE.
           MOVE 987654321 TO TOOLARGE.
           DISPLAY SMALL.
           DISPLAY MEDIUM.
           DISPLAY LARGE.
           DISPLAY TOOLARGE.
           STOP RUN.
