       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTEXPLICITWIDTHSTRING.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 STR1 PIC X(10).
       01 STR2 PIC X(5).

       PROCEDURE DIVISION.

       MAIN SECTION.
           MOVE "Short" TO STR1.
           MOVE "Exact" TO STR2.
           DISPLAY STR1.
           DISPLAY STR2.
           GOBACK.
