       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTLARGEINTEGERS.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-LARGEVALUE PIC 9(10).
       01 GRACE-RESULT PIC 9(10).

      *GRACE Compiler Helper Variables
       01 GRACE-TMP-INT PIC 9(6).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE 2147483647 TO GRACE-LARGEVALUE.
           COMPUTE GRACE-RESULT = GRACE-LARGEVALUE + 1.
           DISPLAY "Large integer: ".
           DISPLAY GRACE-LARGEVALUE.
           DISPLAY "After adding 1: ".
           DISPLAY GRACE-RESULT.
           GOBACK.
