       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTHELLO.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GREETING PIC X(30).
       01 NAME PIC X(30).

       PROCEDURE DIVISION.
           MOVE "Hello" TO GREETING.
           MOVE "Arnav" TO NAME.
           DISPLAY GREETING.
           DISPLAY NAME.
           STOP RUN.
