       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTPRINTEXPR.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-A PIC 9(3).
       01 GRACE-B PIC 9(2).

      *GRACE Compiler Helper Variables
       01 GRACE-TMP-INT-1 PIC S9(18).
       01 GRACE-TMP-DISPLAY PIC Z(17)9-.

       PROCEDURE DIVISION.
       MAIN SECTION.
           COMPUTE GRACE-A = 100.
           COMPUTE GRACE-B = 23.
           COMPUTE GRACE-TMP-INT-1 = GRACE-A + GRACE-B.
           MOVE GRACE-TMP-INT-1 TO GRACE-TMP-DISPLAY.
           DISPLAY FUNCTION TRIM(GRACE-TMP-DISPLAY).
           DISPLAY 20.
           DISPLAY GRACE-A.
           GOBACK.
