       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTINT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-ANOTHER PIC 9(1).
       01 GRACE-COUNT PIC 9(3).

       PROCEDURE DIVISION.
       MAIN SECTION.
           COMPUTE GRACE-COUNT = 123.
           DISPLAY GRACE-COUNT.
           COMPUTE GRACE-ANOTHER = 0.
           DISPLAY GRACE-ANOTHER.
           GOBACK.
