       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTLARGEINTEGERS.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-LARGEVALUE PIC 9(10).
       01 GRACE-RESULT PIC 9(10).

      *GRACE Compiler Helper Variables
       01 GRACE-TMP-INT-1 PIC S9(18).
       01 GRACE-TMP-DISPLAY PIC Z(17)9-.

       PROCEDURE DIVISION.
       MAIN SECTION.
           COMPUTE GRACE-LARGEVALUE = 2147483647.
           COMPUTE GRACE-RESULT = GRACE-LARGEVALUE + 1.
           DISPLAY "Large integer: ".
           DISPLAY GRACE-LARGEVALUE.
           DISPLAY "After adding 1: ".
           DISPLAY GRACE-RESULT.
           GOBACK.
