       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTCONST.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-MAX-VALUE PIC 9(3).
       01 GRACE-GREETING PIC X(11).

       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE "Hello Const" TO GRACE-GREETING.
           DISPLAY GRACE-GREETING.
           COMPUTE GRACE-MAX-VALUE = 999.
           DISPLAY GRACE-MAX-VALUE.
           GOBACK.
