       IDENTIFICATION DIVISION.
       PROGRAM-ID. TESTRETURNWIDTHINFERENCE.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GRACE-CODE PIC 9(6).
       01 GRACE-MSG PIC X(30).

      *GRACE Procedure Return Variables
       01 GRACE-RET-GETDEFAULTCODE PIC 9(6).
       01 GRACE-RET-GETDEFAULTMESSAGE PIC X(30).

       PROCEDURE DIVISION.
       DECLARATIVES.
       GRACE-GETDEFAULTMESSAGE SECTION.
           MOVE "Default Message" TO GRACE-RET-GETDEFAULTMESSAGE.
           EXIT SECTION.

       GRACE-GETDEFAULTCODE SECTION.
           COMPUTE GRACE-RET-GETDEFAULTCODE = 999.
           EXIT SECTION.

       END DECLARATIVES.

       MAIN SECTION.
           PERFORM GRACE-GETDEFAULTMESSAGE.
           MOVE GRACE-RET-GETDEFAULTMESSAGE TO GRACE-MSG.
           PERFORM GRACE-GETDEFAULTCODE.
           COMPUTE GRACE-CODE = GRACE-RET-GETDEFAULTCODE.
           DISPLAY GRACE-MSG.
           DISPLAY GRACE-CODE.
           GOBACK.
